@startuml "ClassValidatorUML"

interface IReceivableService {
  create(command: CreateReceivableDTO)
}

class Receivable {
  readonly id: string
  readonly amount: number
  readonly issueDate: Date
  readonly createdAt: Date
  readonly updatedAt: Date
  readonly customerId: string

  constructor(props: Receivable)
}

class CreateReceivableDTO extends Receivable {
  constructor(props: CreateReceivableDTO)
}

note bottom of CreateReceivableDTO : extends OmitType(Receivable, ['id', 'createdAt', 'updatedAt'])

abstract class Validator<T> {
  validate(obj: T): ValidationErrors<T>
}

note top of Validator : fluentvalidation-ts abstract class

abstract ClassValidator<T> extends Validator {
  validateAndThrow(object: T): void
}

class CreateReceivableDTOValidator extends ClassValidator {
  - {static} validator: CreateReceivableDTOValidator

  constructor()
  {static} createInstance(): CreateReceivableDTOValidator
  {static} getInstance(): CreateReceivableDTOValidator
}

exception CoreException extends Error {
  readonly key: string
  readonly message: string
  readonly data?: object

  constructor(coreError: CoreError)
}

interface CoreError {
  key: string
  message: string
  data?: object
}

CoreException --[hidden]r> CoreError

CoreException --[hidden]l> ValidationErrors

interface ValidationErrors<T> {
  [Key in keyof T]?: string
}

exception ValidationException<T> extends CoreException {
  constructor(error: Omit<CoreError, 'key'>, validationErrors: ValidationErrors<T>, submittedObj: T)
}


@enduml